### ISSUE TITLE
小米手机上崩溃

### ISSUE THREAD

**Issue by vipycm** [Zackratos/UltimateBarX#27]
2021-01-28 11:43:52.083 17441-17441/com.pionex.lite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pionex.lite, PID: 17441
    java.lang.StackOverflowError: stack size 8192KB
        at android.util.MemoryIntArray.enforceValidIndex(MemoryIntArray.java:212)
        at android.util.MemoryIntArray.get(MemoryIntArray.java:107)
        at android.provider.Settings$GenerationTracker.readCurrentGeneration(Settings.java:2196)
        at android.provider.Settings$GenerationTracker.isGenerationChanged(Settings.java:2180)
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2310)
        at android.provider.Settings$Global.getStringForUser(Settings.java:14009)
        at android.provider.Settings$Global.getString(Settings.java:13997)
        at android.provider.Settings$Global.getInt(Settings.java:14179)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.fullScreenGestureOn(MiuiRom.kt:20)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:18)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
2021-01-28 11:43:52.085 17441-17441/com.pionex.lite E/AndroidRuntime:     at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
2021-01-28 11:43:52.870 17441-17441/com.pionex.lite I/chatty: uid=10230(com.pionex.lite) identical 1872 lines
2021-01-28 11:43:52.870 17441-17441/com.pionex.lite E/AndroidRuntime:     at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
2021-01-28 11:43:52.871 17441-17441/com.pionex.lite E/AndroidRuntime:     at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.UltimateBarXExposedKt.getNavigationBarHeight(UltimateBarXExposed.kt:26)
        at com.zackratos.ultimatebarx.library.rom.MiuiRom.screenIndicatorOn(MiuiRom.kt:25)
        at com.zackratos.ultimatebarx.library.rom.BaseRom.navigationBarExist(BaseRom.kt:19)
        at com.zackratos.ultimatebarx.library.core.UltimateBarXKt.updateNavigationBarView(UltimateBarX.kt:139)
        at com.zackratos.ultimatebarx.library.core.UltimateBarXKt.updateNavigationBar(UltimateBarX.kt:69)
        at com.zackratos.ultimatebarx.library.core.UltimateBarXKt.defaultNavigationBar(UltimateBarX.kt:105)
        at com.zackratos.ultimatebarx.library.operator.ActivityOperator.applyStatusBar(ActivityOperator.kt:27)
        at com.pionex.lite.BaseReactActivity.onCreate(BaseReactActivity.java:26)
        at com.pionex.lite.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7893)
2021-01-28 11:43:52.871 17441-17441/com.pionex.lite E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7584)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Zackratos** [comment]
手机型号是什么

**Comment by cjlkbxt** [comment]
我也遇到了，小米9

**Comment by Zackratos** [comment]
感谢反馈，问题已修复，可以使用 0.4.3 版本
@vipycm @cjlkbxt
