### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ericwangjp** [Zackratos/UltimateBarX#45]
crash了，fragment一般都是在onCreateView()中设置的，Google官方建议的初始化方法也是onCreate()或者onCreateView(),这个库只能在onCreateView()之后在fragment中使用?

java.lang.IllegalStateException: Fragment HomeFragment{19cbea8} (3ebf211b-78e4-4379-998a-34caeb0aa6fc id=0x7f0800d6 tag=HOME) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:1964)
        at com.zackratos.ultimatebarx.ultimatebarx.core.CoreKt.addFrameLayoutWrapper(Core.kt:172)
        at com.zackratos.ultimatebarx.ultimatebarx.core.CoreKt.ultimateBarXInitialization(Core.kt:53)
        at com.zackratos.ultimatebarx.ultimatebarx.OperatorKt.applyStatusBar(Operator.kt:44)
        at com.zackratos.ultimatebarx.ultimatebarx.UltimateBarXKt.statusBar(UltimateBarX.kt:88)
        at com.zackratos.ultimatebarx.ultimatebarx.UltimateBarXKt.statusBar(UltimateBarX.kt:23)
        at com.redflag.baselib.ui.BaseFragment.setStatusBar(BaseFragment.kt:81)
        at com.redflag.baselib.ui.BaseFragment.onCreateView(BaseFragment.kt:40)

**Comment by Zackratos** [comment]
是的，因为在 `onCreate` 里面拿不到当前 `Fragment` 的 `rootView`， 但是我的实现又是依赖 `rootView` 的，所以必须在 `onCreateView` 之后使用
