### ISSUE TITLE
偶现崩溃 lateinit property context has not been initialized

### ISSUE THREAD

**Issue by xilost** [Zackratos/UltimateBarX#59]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
	at com.weibo.wbalk.app.utils.ultimatebarx.UltimateBarXManager.getContext$app_release(UltimateBarXManager.kt:34)
	at com.weibo.wbalk.app.utils.ultimatebarx.UltimateBarXExposedKt.getStatusBarHeight(UltimateBarXExposed.kt:17)
	at com.weibo.wbalk.app.utils.ultimatebarx.core.UltimateBarXKt.setStatusBarPadding(UltimateBarX.kt:217)
	at com.weibo.wbalk.app.utils.ultimatebarx.core.UltimateBarXKt.updateStatusBarView(UltimateBarX.kt:133)
	at com.weibo.wbalk.app.utils.ultimatebarx.core.UltimateBarXKt.updateStatusBar(UltimateBarX.kt:63)
	at com.weibo.wbalk.app.utils.ultimatebarx.operator.ActivityOperator.applyStatusBar(ActivityOperator.kt:26)
	at com.weibo.wbalk.mvp.ui.activity.MainTabActivity.initData(MainTabActivity.java:266)
	at com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:108)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)

 三星note8  Android 9.0

**Comment by renzhe2015** [comment]
请问这个问题有方法修复吗

**Comment by Zackratos** [comment]
> 请问这个问题有方法修复吗

怎么触发的

**Comment by renzhe2015** [comment]
就是普通调用然后进入app

**Comment by renzhe2015** [comment]
UltimateBarXManage里的context能否够改成不是lateinit的呢

**Comment by ZackLee** [comment]
这个问题在多进程必现，我在我的项目里做了兼容，如果有必要我可以提个PR @Zackratos

**Comment by chenkexu** [comment]
@ZackLee 最后怎么解决的？

**Comment by zhengtingguang** [comment]
![image](https://user-images.githubusercontent.com/14228431/215689692-2ce64dc1-eb5a-4745-b7c0-3ef9eccb8737.png)
崩溃还是挺多的，有优化context的懒加载吗？

**Comment by zhengtingguang** [comment]
![image](https://user-images.githubusercontent.com/14228431/215689858-996b2a4b-501c-4ede-afbe-03ed165f2e92.png)
崩溃还是挺多的，有优化context的懒加载吗
